# Generated by Django 4.1.6 on 2023-11-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(default='Your default long description here'),
        ),
    ]
